### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Vessel-arch** [ispc-lab/GSC#5]
我下载了数据集和代码，并安装了相应的模块，也设置完成了data_root，在第一次运行代码后出现了如下的情况：
Traceback (most recent call last):
  File "run.py", line 79, in <module>
    main()
  File "run.py", line 62, in main
    shutil.copy(args.config, os.path.join(cfg.result_path, cfg.name, cfg.version, args.config.split('/')[-1]))
  File "E:\sspm\lib\shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "E:\sspm\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'work_dirs/results\\STAttnsGraphDashcam\\2.0.0\\config.py'
我去查看了一下，似乎代码中并没有在work_dirs中建立results和logs这两个文件夹，只建立了checkpoints，请问这是否是个bug，我该修改哪一部分来解决

**Comment by nekoscratch01** [comment]
> 我下载了数据集和代码，并安装了相应的模块，也设置完成了data_root，在第一次运行代码后出现了如下的情况： Traceback (most recent call last): File "run.py", line 79, in main() File "run.py", line 62, in main shutil.copy(args.config, os.path.join(cfg.result_path, cfg.name, cfg.version, args.config.split('/')[-1])) File "E:\sspm\lib\shutil.py", line 245, in copy copyfile(src, dst, follow_symlinks=follow_symlinks) File "E:\sspm\lib\shutil.py", line 121, in copyfile with open(dst, 'wb') as fdst: FileNotFoundError: [Errno 2] No such file or directory: 'work_dirs/results\STAttnsGraphDashcam\2.0.0\config.py' 我去查看了一下，似乎代码中并没有在work_dirs中建立results和logs这两个文件夹，只建立了checkpoints，请问这是否是个bug，我该修改哪一部分来解决

I'm facing a similar issue. It seems there could be some problems either within the code itself or with the dependencies. as I spent so much time on this, I am more incline on the previous one

**Comment by Vessel-arch** [comment]
> > 我下载了数据集和代码，并安装了相应的模块，也设置完成了data_root，在第一次运行代码后出现了如下的情况： Traceback (most recent call last): File "run.py", line 79, in main() File "run.py", line 62, in main shutil.copy(args.config, os.path.join(cfg.result_path, cfg.name, cfg.version, args.config.split('/')[-1])) File "E:\sspm\lib\shutil.py", line 245, in copy copyfile(src, dst, follow_symlinks=follow_symlinks) File "E:\sspm\lib\shutil.py", line 121, in copyfile with open(dst, 'wb') as fdst: FileNotFoundError: [Errno 2] No such file or directory: 'work_dirs/results\STAttnsGraphDashcam\2.0.0\config.py' 我去查看了一下，似乎代码中并没有在work_dirs中建立results和logs这两个文件夹，只建立了checkpoints，请问这是否是个bug，我该修改哪一部分来解决
> 
> I'm facing a similar issue. It seems there could be some problems either within the code itself or with the dependencies. as I spent so much time on this, I am more incline on the previous one

我就简单的额外新建了results文件夹，跑通代码了，但是现在发现明明代码都没变，测试集的准确率却一直不高，最高只有48。训练集的准确率开始也很高，维持在60，70多，但是训练到200多轮的时候出现严重的震荡，会从60多跳到40多，甚至跳到0，我都不知道是我的问题还是有什么额外的训练方法我没搞清楚？
